[package]
name = "rfmp"
version = "0.1.8"
authors = ["JohnTheCoolingFan <ivan8215145640@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
zip = { version = "0.5", features = [ "deflate", "deflate-zlib" ], default-features = false }
mtzip = "0.1"
walkdir = "2"
dirs = "4"
glob = "0.3"

[profile.release]
lto = true
codegen-units = 1
