[package]
name = "rfmp"
version = "0.1.16"
authors = ["JohnTheCoolingFan <ivan8215145640@gmail.com>"]
edition = "2021"
description = "A program to pack and install Factorio mods from source code quickly"
license = "MIT"
homepage = "https://discord.gg/rqkaeYJhzS"
repository = "https://github.com/JohnTheCoolingFan/rfmp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
mtzip = "0.7"
walkdir = "2"
dirs = "4"
glob = "0.3"
clap = { version="4.2", features = ["derive"] }
