[package]
name = "rfmp"
version = "0.1.7"
authors = ["JohnTheCoolingFan <ivan8215145640@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
zip = { version = "0.5", features = [ "deflate", "deflate-zlib" ], default-features = false }
walkdir = "2"
dirs = "3"
glob = "0.3"

[profile.release]
panic = 'abort'
