[package]
name = "rfmp"
version = "0.1.10"
authors = ["JohnTheCoolingFan <ivan8215145640@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
mtzip = "0.3"
walkdir = "2"
dirs = "4"
glob = "0.3"
sysinfo = "0.25"
clap = { version="3.2", features = ["derive"] }
